name: Build Android

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # test rebuild

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: android32

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-build
          path: build/**/*.geode
