name: Build Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Geode CLI
        run: |
          pip install git+https://github.com/geode-sdk/cli

      - name: Install Geode SDK
        run: |
          geode sdk install

      - name: Build Mod
        run: |
          geode build -p android

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AI-Level-Generator-Pro
          path: build/**/*.geode
